id: I06240925
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:32:47.184727'
last_modified: '2022-05-30T18:32:47.184747'
parser: null
source_metadata:
  title: Chokling Tersé Tulku
  language: bo
  description: 'Texts by and about Chokling Tersé Tulku, Gyurme Tsewang Tenpel (''gyur
    med tshe dbang bstan ''phel, 1889–1956):'
  volume:
    f2E33:
      title: 'Cloud-Banks of the Two Accumulations: A Feast Offering Including the
        Six Vajra Lines Prayer to Be Practiced with Any Guru Sādhana'
      base_file: f2E33.txt
      order: 1
      parent: Tsok
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
